# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.4.0.schema.json

PackageIdentifier: Speed-Soft.Time-Sync.Client
PackageVersion: 1.9.0.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.4.0
